export const FETCH_USER_LIST_REQUEST = "FETCH_USER_LIST_REQUEST"
export const FETCH_USER_LIST_SUCCESS = "FETCH_USER_LIST_SUCCESS"
export const FETCH_USER_LIST_FAILURE = "FETCH_USER_LIST_FAILURE"

export const FETCH_USER_PROFILE_DETAILS_REQUEST = "FETCH_USER_PROFILE_DETAILS_REQUEST"
export const FETCH_USER_PROFILE_DETAILS_SUCCESS = "FETCH_USER_PROFILE_DETAILS_SUCCESS"
export const FETCH_USER_PROFILE_DETAILS_FAILURE = "FETCH_USER_PROFILE_DETAILS_FAILURE"